apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: sandbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: index.docker.io/ezcater/jenkins:2.90
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 3
        env:
        - name: JAVA_OPTS
          value: '-Xmx800m'
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources:
          limits:
            cpu: 500m
            memory: 800Mi
          requests:
            cpu: 500m
            memory: 800Mi
      imagePullSecrets:
      - name: regsecret
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      volumes:
      - name: jenkins-home
        emptyDir: {}
