apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
  namespace: sandbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: index.docker.io/phantasm66/redis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      imagePullSecrets:
      - name: regsecret
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always

